<?php

namespace Backoffice\Products\Domain\Service;

use App\Backoffice\Products\Domain\Port\ProductRepository;
use App\Backoffice\Products\Domain\Product;
use App\Backoffice\Products\Domain\Service\ProductFinder;
use App\Backoffice\Products\Domain\ValueObject\ProductDescription;
use App\Backoffice\Products\Domain\ValueObject\ProductImage;
use App\Backoffice\Products\Domain\ValueObject\ProductName;
use App\Backoffice\Products\Domain\ValueObject\ProductPrice;
use App\Shared\Domain\Identifier\UserId;
use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\MockObject\MockObject;
use Tests\Stub\ProductMother;
use Tests\TestCase;

#[Group('domain')]
#[Group('backoffice')]
#[Group('backoffice-products')]
class ProductFinderTest extends TestCase
{
    private ProductFinder $productFinder;
    private MockObject $repository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repository = $this->createMock(ProductRepository::class);
        $this->productFinder = new ProductFinder($this->repository);
    }

    public function testItShouldReturnNull(): void
    {
        $result =$this->productFinder->__invoke('nonexistentid');
        $this->assertNull($result);
    }

    public function testItShouldReturnProduct(): void
    {
        $product = ProductMother::son();

        $this->repository->expects($this->once())
            ->method('search')
            ->with($product->getId())
            ->willReturn($product);

        $result = $this->productFinder->__invoke($product->getId());

        $this->assertEquals($product->getId(), $result->getId());
        $this->assertEquals($product->getName(), $result->getName());
        $this->assertEquals($product->getDescription(), $result->getDescription());
        $this->assertEquals($product->getImage(), $result->getImage());
        $this->assertEquals($product->getPrice(), $result->getPrice());
        $this->assertEquals($product->getCreatedBy(), $result->getCreatedBy());
        $this->assertEquals($product->getUpdatedBy(), $result->getUpdatedBy());
        $this->assertEquals($product->getCreatedAt(), $result->getCreatedAt());
        $this->assertEquals($product->getUpdatedAt(), $result->getUpdatedAt());
        $this->assertEquals($product->getDeletedAt(), $result->getDeletedAt());
        $this->assertEquals($product->getDeletedBy(), $result->getDeletedBy());
    }
}
