<?php

namespace Backoffice\Products\Domain\Service;

use App\Backoffice\Products\Domain\Exceptions\ProductDoesntExist;
use App\Backoffice\Products\Domain\Port\ProductRepository;
use App\Backoffice\Products\Domain\Product;
use App\Backoffice\Products\Domain\Service\ProductFinder;
use App\Backoffice\Products\Domain\Service\ProductRemover;
use App\Backoffice\Products\Domain\ValueObject\ProductDescription;
use App\Backoffice\Products\Domain\ValueObject\ProductImage;
use App\Backoffice\Products\Domain\ValueObject\ProductName;
use App\Backoffice\Products\Domain\ValueObject\ProductPrice;
use App\Shared\Domain\Identifier\UserId;
use PHPUnit\Framework\MockObject\MockObject;
use Tests\TestCase;

class ProductRemoverTest extends TestCase
{
    private MockObject $productFinder;
    private ProductRemover $productRemover;
    private ProductRepository $repository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->productFinder = $this->createMock(ProductFinder::class);
        $this->repository = $this->createMock(ProductRepository::class);
        $this->productRemover = new ProductRemover($this->repository, $this->productFinder);
    }

    public function testShouldRemoveProduct(): void
    {
        $name = ProductName::create('Product Name');
        $description = ProductDescription::create('Product Description');
        $image = ProductImage::create('https://example.com/product-image.jpg');
        $price = ProductPrice::create(100);
        $creatorId = UserId::generate();

        $product = Product::create($name, $description, $image, $price, $creatorId);

        $this->productFinder->expects($this->once())
            ->method('__invoke')
            ->with($product->getId())
            ->willReturn($product);

        $deleted = $this->productRemover->__invoke($product->getId());

        $this->assertTrue($deleted->isDeleted());
    }

    public function testShouldThrowProductDoesntExistException()
    {
        $this->expectException(ProductDoesntExist::class);
        $this->productRemover->__invoke('nonexisentProductId');
    }
}
