<?php

namespace Tests\Backoffice\BackofficeProductPurchase\Domain;

use App\Backoffice\BackofficeProductPurchases\Domain\Exception\OutOfStock;
use Tests\Stub\BackofficeProductPurchaseMother;
use Tests\TestCase;

class BackofficeProductPurchaseTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testItShouldUpdateExpense()
    {
        $purchase = BackofficeProductPurchaseMother::son(
            quantity: 3,
            expenses: 0,
        );

        $purchase->generateExpense(1);

        $this->assertEquals(1, $purchase->getExpenses());
    }

    public function testItShouldThrowOutOfStock()
    {
        $purchase = BackofficeProductPurchaseMother::son(
            quantity: 3,
            expenses: 3,
        );

        $this->expectException(OutOfStock::class);
        $purchase->generateExpense(1);
    }
}
