<?php

namespace Tests\Backoffice\Products\Application;

use App\Backoffice\Products\Application\Update\UpdateProductCommand;
use App\Backoffice\Products\Application\Update\UpdateProductCommandHandler;
use App\Backoffice\Products\Domain\Service\ProductUpdater;
use App\Shared\Domain\Identifier\UserId;
use PHPUnit\Framework\MockObject\MockObject;
use Tests\Stub\Backoffice\ProductMother;
use Tests\TestCase;

class UpdateProductCommandTest extends TestCase
{
    private MockObject $updater;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->updater = $this->createMock(ProductUpdater::class);
    }

    public function testUpdateProduct(): void
    {
        $product = ProductMother::son();
        $updated = ProductMother::son(id: $product->getId());
        $updater = UserId::generate()->value();

        $id = $product->getId();
        $name = $updated->getName();
        $description = $updated->getDescription();
        $image = $updated->getImage();
        $price  = $updated->getPrice();

        $this->updater->expects($this->once())
            ->method('__invoke')
            ->with($updater, $id, $name, $description, $price, $image)
            ->willReturn($updated);

        $command = UpdateProductCommand::create(
            activeUserId: $updater,
            id: $id,
            name: $name,
            description: $description,
            price: $price,
            image: $image,
        );

        $handler = new UpdateProductCommandHandler($this->updater);

        $handler($command);
    }
}
