<?php

namespace Tests\Backoffice\User\Domain\Service;

use App\Backoffice\User\Domain\Exception\DuplicatedUserEmail;
use App\Backoffice\User\Domain\Exception\UserAlreadyExist;
use App\Backoffice\User\Domain\Port\UserRepository;
use App\Backoffice\User\Domain\Services\PasswordValidator;
use App\Backoffice\User\Domain\Services\UserCreator;
use App\Backoffice\User\Domain\Services\UserFinder;
use App\Backoffice\User\Domain\ValueObject\UserEmail;
use App\Backoffice\User\Domain\ValueObject\UserHashPassword;
use App\Backoffice\User\Domain\ValueObject\UserName;
use PHPUnit\Framework\MockObject\MockObject;
use Tests\Stub\UserMother;
use Tests\TestCase;

class UserCreatorTest extends TestCase
{
    private UserCreator $userCreator;
    private MockObject $userFinder;
    private MockObject $passwordValidator;
    private MockObject $repository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->userFinder = $this->createMock(UserFinder::class);
        $this->repository = $this->createMock(UserRepository::class);
        $this->passwordValidator = $this->createMock(PasswordValidator::class);
        $this->userCreator = new UserCreator($this->repository, $this->userFinder, $this->passwordValidator);
    }

    public function testItShouldCreateUser(): void
    {
        $user = UserMother::son();

        $name = UserName::create($user->getName());
        $email = UserEmail::create($user->getEmail());
        $password = '1234'; // Mocked

        $mockedHash = UserHashPassword::generate();
        $this->passwordValidator
            ->expects($this->once())
            ->method('validateAndHash')
            ->with($password)
            ->willReturn([
                'success' => true,
                'hash' => $mockedHash,
            ]);

        $this->userFinder
            ->expects($this->once())
            ->method('findById')
            ->willReturn(null);

        $this->userFinder
            ->expects($this->once())
            ->method('findByEmail')
            ->willReturn(null);

        $result = $this->userCreator->__invoke($name, $email, $password);

        $this->assertEquals($name->value(), $result->getName());
        $this->assertEquals($email->value(), $result->getEmail());
        $this->assertEquals($mockedHash->value(), $result->getPassword());
    }

    public function testItShouldFailOnDuplicatedUser(): void
    {
        $user = UserMother::son();

        $name = UserName::create($user->getName());
        $email = UserEmail::create($user->getEmail());
        $password = '1234'; // Mocked

        $mockedHash = UserHashPassword::generate();
        $this->passwordValidator
            ->expects($this->once())
            ->method('validateAndHash')
            ->with($password)
            ->willReturn([
                'success' => true,
                'hash' => $mockedHash,
            ]);

        $this->userFinder
            ->expects($this->once())
            ->method('findById')
            ->willReturn($user);

        $this->expectException(UserAlreadyExist::class);
        $this->userCreator->__invoke($name, $email, $password);
    }

    public function testItShouldFailOnDuplicatedEmail(): void
    {
        $user = UserMother::son();

        $name = UserName::create($user->getName());
        $email = UserEmail::create($user->getEmail());
        $password = '1234'; // Mocked

        $mockedHash = UserHashPassword::generate();
        $this->passwordValidator
            ->expects($this->once())
            ->method('validateAndHash')
            ->with($password)
            ->willReturn([
                'success' => true,
                'hash' => $mockedHash,
            ]);

        $this->userFinder
            ->expects($this->once())
            ->method('findById')
            ->willReturn(null);

        $this->userFinder
            ->expects($this->once())
            ->method('findByEmail')
            ->willReturn($user);

        $this->expectException(DuplicatedUserEmail::class);
        $this->userCreator->__invoke($name, $email, $password);
    }
}
